import FormalMultilinearGeometricAnalytic_v1
import HomogeneousPolynomialSeriesAnalytic_v1

-- Human-readable physical definitions.

-- Expanded types expose mathematical implicit arguments; declaration bodies stay in source.
-- Instance implementations are suppressed; proof arguments in types are printed.
set_option pp.all true
set_option pp.universes true
set_option pp.instances false
set_option pp.proofs true
set_option pp.maxSteps 2000000
set_option maxRecDepth 16384
set_option pp.rawOnError true
#check @TheoremT.Continuum.formalMultilinearSeries_radius_geometric
#check @TheoremT.Continuum.formalMultilinearSeries_analyticAt_geometric
#check @TheoremT.Continuum.formalMultilinearSeries_analyticOnNhd_geometric
#check @TheoremT.Continuum.homogeneousPolynomialMultilinearSeries
#check @TheoremT.Continuum.homogeneousPolynomialMultilinearSeries_diagonal
#check @TheoremT.Continuum.homogeneousPolynomialMultilinearSeries_norm
#check @TheoremT.Continuum.homogeneousPolynomialMultilinearSeries_sum
#check @TheoremT.Continuum.homogeneous_polynomial_series_analyticOnNhd
#check @TheoremT.Continuum.homogeneous_polynomial_series_analyticOnNhd_closed_polydisc
#check @TheoremT.Continuum.shifted_homogeneous_polynomial_series_analyticOnNhd

set_option pp.all false
set_option pp.universes false
-- Kernel axiom dependencies for every local declaration.
#print axioms TheoremT.Continuum.formalMultilinearSeries_radius_geometric
#print axioms TheoremT.Continuum.formalMultilinearSeries_analyticAt_geometric
#print axioms TheoremT.Continuum.formalMultilinearSeries_analyticOnNhd_geometric
#print axioms TheoremT.Continuum.homogeneousPolynomialMultilinearSeries
#print axioms TheoremT.Continuum.homogeneousPolynomialMultilinearSeries_diagonal
#print axioms TheoremT.Continuum.homogeneousPolynomialMultilinearSeries_norm
#print axioms TheoremT.Continuum.homogeneousPolynomialMultilinearSeries_sum
#print axioms TheoremT.Continuum.homogeneous_polynomial_series_analyticOnNhd
#print axioms TheoremT.Continuum.homogeneous_polynomial_series_analyticOnNhd_closed_polydisc
#print axioms TheoremT.Continuum.shifted_homogeneous_polynomial_series_analyticOnNhd
