#!/usr/bin/env python3
"""Render STATUS.md from claims/registry.yaml. With --check, fail if STATUS.md is stale."""
from __future__ import annotations

import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
TIER_NAMES = {
    "L": "Lean-verified", "C": "Certified computation", "P2": "Reviewed paper proof",
    "P1": "Unreviewed paper proof", "N": "Numerical evidence", "O": "Open", "X": "Withdrawn / trivial",
}
SECTORS = {
    "S1": ("Operator-theoretic foundations", "sectors/S1-foundations"),
    "S2": ("Two-electron theory and Theorem T", "sectors/S2-two-electron-theory"),
    "S3": ("Certified energy intervals", "sectors/S3-certified-computation"),
    "S4": ("Three electrons", "sectors/S4-three-electrons"),
    "S5": ("Algorithms for arbitrary N", "sectors/S5-arbitrary-N"),
    "S6": ("Molecules and efficient methods", "sectors/S6-molecules"),
    "S7": ("Complexity", "sectors/S7-complexity"),
    "S8": ("Regularity and approximation", "sectors/S8-regularity-approximation"),
    "S9": ("Lattice and model Hamiltonians", "sectors/S9-lattice-models"),
}


def render() -> str:
    claims = yaml.safe_load((ROOT / "claims" / "registry.yaml").read_text())["claims"]
    out = [
        "# Status",
        "",
        "<!-- Generated by tools/render_status.py from claims/registry.yaml. Do not edit by hand. -->",
        "",
        "Every result in this repository and its evidence tier. The tiers are defined in "
        "[CONTRIBUTING.md](CONTRIBUTING.md) §1. Only **L**, **C** and **P2** results are established "
        "and can be built on. **P1** means a written proof that no human has independently reviewed.",
        "",
        "| Tier | Meaning | Count |",
        "|---|---|---|",
    ]
    for t, name in TIER_NAMES.items():
        out.append(f"| **{t}** | {name} | {sum(1 for c in claims if c['tier'] == t)} |")
    for s, (title, path) in SECTORS.items():
        rows = [c for c in claims if c["sector"] == s]
        out += ["", f"## {s}: [{title}]({path}/README.md)", ""]
        if not rows:
            out.append("No claims yet. See the sector README for open problems.")
            continue
        out += ["| ID | Result | Tier | Conditional on |", "|---|---|---|---|"]
        for c in rows:
            cid = c["id"]
            card = c.get("card")
            label = f"[{cid}]({card})" if card else cid
            if c["tier"] == "X" and c.get("erratum"):
                label += f" ([erratum]({c['erratum']}))"
            cond = "; ".join(x.rstrip(". ") for x in c.get("conditional_on") or []) or "none"
            title_ = c["title"].replace("|", "\\|")
            out.append(f"| {label} | {title_} | **{c['tier']}** | {cond.replace('|', '/')} |")
    return "\n".join(out) + "\n"


def main() -> int:
    text = render()
    target = ROOT / "STATUS.md"
    if "--check" in sys.argv:
        if not target.exists() or target.read_text() != text:
            print("render_status: STATUS.md is out of date; run python3 tools/render_status.py")
            return 1
        print("render_status: STATUS.md is up to date")
        return 0
    target.write_text(text)
    print("render_status: wrote STATUS.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
